/* Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>

main() {
  int n0, n1, intermed, sum;
  n0 = 1;
  n1 = 2;
  sum = 0;
  while (n1 <= 4000000) {
    if (n1 % 2 == 0)
      sum = sum + n1;
    intermed = n1;
    n1 = n1 + n0;
    n0 = intermed;
  }
  printf("%d\n",sum);
}
